# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_login(object):
    def setupUi(self, Tela_Inicio):
        Tela_Inicio.setObjectName("Tela_Inicio")
        Tela_Inicio.resize(396, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tela_Inicio.sizePolicy().hasHeightForWidth())
        Tela_Inicio.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Logo_JA_50x50.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Tela_Inicio.setWindowIcon(icon)
        Tela_Inicio.setStyleSheet("\n"
"background-color: rgb(68, 68, 68);")
        self.centralwidget = QtWidgets.QWidget(Tela_Inicio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("color: rgb(218, 218, 218);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(68, 68, 70);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Introducao = QtWidgets.QLabel(self.frame_2)
        self.Introducao.setObjectName("Introducao")
        self.horizontalLayout_2.addWidget(self.Introducao)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("nova_imagem.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QLineEdit {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 60, 60);\n"
"    selection-background-color: lightgray; /* Cor de fundo da seleção de texto */\n"
"    selection-color: black; /* Cor do texto selecionado */\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: gray; /* Cor da borda */\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: lightgray; /* Cor da borda quando o mouse está sobre o widget */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: dodgerblue; /* Cor da borda quando o widget está em foco */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QLineEdit {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 60, 60);\n"
"    selection-background-color: lightgray; /* Cor de fundo da seleção de texto */\n"
"    selection-color: black; /* Cor do texto selecionado */\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: gray; /* Cor da borda */\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: lightgray; /* Cor da borda quando o mouse está sobre o widget */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: dodgerblue; /* Cor da borda quando o widget está em foco */\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setStyleSheet("QLabel {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Sair = QtWidgets.QPushButton(self.frame_5)
        self.Sair.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 60, 60);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Sair.setObjectName("Sair")
        self.horizontalLayout.addWidget(self.Sair)
        self.Login = QtWidgets.QPushButton(self.frame_5)
        self.Login.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 60, 60);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Login.setObjectName("Login")
        self.horizontalLayout.addWidget(self.Login)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame)
        Tela_Inicio.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Tela_Inicio)
        self.statusBar.setObjectName("statusBar")
        Tela_Inicio.setStatusBar(self.statusBar)

        self.retranslateUi(Tela_Inicio)
        QtCore.QMetaObject.connectSlotsByName(Tela_Inicio)

    def retranslateUi(self, Tela_Inicio):
        _translate = QtCore.QCoreApplication.translate
        Tela_Inicio.setWindowTitle(_translate("Tela_Inicio", "Login"))
        self.Introducao.setText(_translate("Tela_Inicio", "Bem vindo de Volta!"))
        self.label.setText(_translate("Tela_Inicio", "Email:"))
        self.label_2.setText(_translate("Tela_Inicio", "Senha"))
        self.Sair.setText(_translate("Tela_Inicio", "Sair"))
        self.Login.setText(_translate("Tela_Inicio", "Login"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_tela_login_user = QtWidgets.QMainWindow()
    ui = Ui_Tela_login()
    ui.setupUi(ui_tela_login_user)
    ui_tela_login_user.show()
    sys.exit(app.exec_())
