# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Principal(object):
    def setupUi(self, Tela_Principal):
        Tela_Principal.setObjectName("Tela_Principal")
        Tela_Principal.resize(1318, 859)
        self.centralwidget = QtWidgets.QWidget(Tela_Principal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1300, 800))
        self.frame.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout.addWidget(self.frame_11, 5, 1, 2, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout.addWidget(self.frame_16, 3, 2, 2, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout.addWidget(self.frame_9, 8, 1, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout.addWidget(self.frame_17, 6, 2, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 30))
        self.frame_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_20 = QtWidgets.QFrame(self.frame_2)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.Logo = QtWidgets.QLabel(self.frame_20)
        self.Logo.setGeometry(QtCore.QRect(40, 20, 47, 13))
        self.Logo.setObjectName("Logo")
        self.horizontalLayout_2.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_2)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_2.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_2)
        self.frame_22.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 60, 60);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.frame_22)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.Saldo = QtWidgets.QLCDNumber(self.frame_22)
        self.Saldo.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.Saldo.setObjectName("Saldo")
        self.verticalLayout_11.addWidget(self.Saldo)
        self.horizontalLayout_2.addWidget(self.frame_22)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout.addWidget(self.frame_10, 7, 1, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout.addWidget(self.frame_19, 9, 2, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout.addWidget(self.frame_12, 4, 1, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout.addWidget(self.frame_18, 8, 2, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout.addWidget(self.frame_8, 9, 1, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_23 = QtWidgets.QFrame(self.frame_15)
        self.frame_23.setStyleSheet("")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        self.frame_25.setStyleSheet("")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Ajuda = QtWidgets.QPushButton(self.frame_25)
        self.Ajuda.setMinimumSize(QtCore.QSize(40, 40))
        self.Ajuda.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Ajuda.setObjectName("Ajuda")
        self.verticalLayout_5.addWidget(self.Ajuda)
        self.horizontalLayout_3.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.frame_23)
        self.frame_26.setStyleSheet("")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Detalhes = QtWidgets.QPushButton(self.frame_26)
        self.Detalhes.setMinimumSize(QtCore.QSize(40, 40))
        self.Detalhes.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Detalhes.setObjectName("Detalhes")
        self.verticalLayout_4.addWidget(self.Detalhes)
        self.horizontalLayout_3.addWidget(self.frame_26)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setStyleSheet("")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Perfil_usuario = QtWidgets.QPushButton(self.frame_24)
        self.Perfil_usuario.setMinimumSize(QtCore.QSize(40, 40))
        self.Perfil_usuario.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Perfil_usuario.setObjectName("Perfil_usuario")
        self.verticalLayout_3.addWidget(self.Perfil_usuario)
        self.horizontalLayout_3.addWidget(self.frame_24)
        self.frame_27 = QtWidgets.QFrame(self.frame_23)
        self.frame_27.setStyleSheet("")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Sair = QtWidgets.QPushButton(self.frame_27)
        self.Sair.setMinimumSize(QtCore.QSize(40, 40))
        self.Sair.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Sair.setObjectName("Sair")
        self.verticalLayout_2.addWidget(self.Sair)
        self.horizontalLayout_3.addWidget(self.frame_27)
        self.horizontalLayout.addWidget(self.frame_23)
        self.gridLayout.addWidget(self.frame_15, 0, 2, 2, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout.addWidget(self.frame_13, 2, 1, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_28 = QtWidgets.QFrame(self.frame_14)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setStyleSheet("")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Redireciona_loja = QtWidgets.QPushButton(self.frame_29)
        self.Redireciona_loja.setMinimumSize(QtCore.QSize(40, 40))
        self.Redireciona_loja.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Redireciona_loja.setObjectName("Redireciona_loja")
        self.verticalLayout_6.addWidget(self.Redireciona_loja)
        self.horizontalLayout_4.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setStyleSheet("")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.extra = QtWidgets.QPushButton(self.frame_30)
        self.extra.setMinimumSize(QtCore.QSize(40, 40))
        self.extra.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.extra.setObjectName("extra")
        self.verticalLayout_7.addWidget(self.extra)
        self.horizontalLayout_4.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_28)
        self.frame_31.setStyleSheet("")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Abr_lista_amigos = QtWidgets.QPushButton(self.frame_31)
        self.Abr_lista_amigos.setMinimumSize(QtCore.QSize(40, 40))
        self.Abr_lista_amigos.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Abr_lista_amigos.setObjectName("Abr_lista_amigos")
        self.verticalLayout_8.addWidget(self.Abr_lista_amigos)
        self.horizontalLayout_4.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_28)
        self.frame_32.setStyleSheet("")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.AdicionarFundos = QtWidgets.QPushButton(self.frame_32)
        self.AdicionarFundos.setMinimumSize(QtCore.QSize(40, 40))
        self.AdicionarFundos.setStyleSheet("QPushButton {\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(50, 50, 50);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.AdicionarFundos.setObjectName("AdicionarFundos")
        self.verticalLayout_9.addWidget(self.AdicionarFundos)
        self.horizontalLayout_4.addWidget(self.frame_32)
        self.verticalLayout_10.addWidget(self.frame_28)
        self.gridLayout.addWidget(self.frame_14, 0, 1, 2, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 50, 70);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setMaximumSize(QtCore.QSize(600, 900))
        self.tableWidget.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(84, 84, 84);\n"
"background-color: rgb(47, 47, 47);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_12.addWidget(self.tableWidget)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 8, 1)
        self.verticalLayout.addWidget(self.frame)
        Tela_Principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Principal)
        QtCore.QMetaObject.connectSlotsByName(Tela_Principal)
        Tela_Principal.setTabOrder(self.Redireciona_loja, self.extra)
        Tela_Principal.setTabOrder(self.extra, self.Abr_lista_amigos)
        Tela_Principal.setTabOrder(self.Abr_lista_amigos, self.AdicionarFundos)
        Tela_Principal.setTabOrder(self.AdicionarFundos, self.Ajuda)
        Tela_Principal.setTabOrder(self.Ajuda, self.Detalhes)
        Tela_Principal.setTabOrder(self.Detalhes, self.Perfil_usuario)
        Tela_Principal.setTabOrder(self.Perfil_usuario, self.Sair)
        Tela_Principal.setTabOrder(self.Sair, self.tableWidget)

    def retranslateUi(self, Tela_Principal):
        _translate = QtCore.QCoreApplication.translate
        Tela_Principal.setWindowTitle(_translate("Tela_Principal", "Jogue Agora"))
        self.Logo.setText(_translate("Tela_Principal", "LOGO"))
        self.label.setText(_translate("Tela_Principal", "SALDO"))
        self.Ajuda.setText(_translate("Tela_Principal", "Ajuda"))
        self.Detalhes.setText(_translate("Tela_Principal", "Detalhes"))
        self.Perfil_usuario.setText(_translate("Tela_Principal", "Perfil"))
        self.Sair.setText(_translate("Tela_Principal", "Sair"))
        self.Redireciona_loja.setText(_translate("Tela_Principal", "Loja"))
        self.extra.setText(_translate("Tela_Principal", "Extra"))
        self.Abr_lista_amigos.setText(_translate("Tela_Principal", "Amigos"))
        self.AdicionarFundos.setText(_translate("Tela_Principal", "Adicionar Fundos"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Tela_Principal", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Tela_Principal", "Preco"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Principal = QtWidgets.QMainWindow()
    ui = Ui_Tela_Principal()
    ui.setupUi(Tela_Principal)
    Tela_Principal.show()
    sys.exit(app.exec_())
