# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Tela_Login_cadastro_user(object):
    def setupUi(self, Ui_Tela_Login_cadastro_user):
        Ui_Tela_Login_cadastro_user.setObjectName("Ui_Tela_Login_cadastro_user")
        Ui_Tela_Login_cadastro_user.resize(732, 801)
        self.centralwidget = QtWidgets.QWidget(Ui_Tela_Login_cadastro_user)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 3px;\n"
"padding: 8px 16px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.Senha_verifica = QtWidgets.QLineEdit(self.frame_8)
        self.Senha_verifica.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Senha_verifica.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Senha_verifica.setObjectName("Senha_verifica")
        self.verticalLayout_5.addWidget(self.Senha_verifica)
        self.gridLayout_2.addWidget(self.frame_8, 1, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.Telefone = QtWidgets.QLineEdit(self.frame_4)
        self.Telefone.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Telefone.setObjectName("Telefone")
        self.verticalLayout_8.addWidget(self.Telefone)
        self.gridLayout_2.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Voltar = QtWidgets.QPushButton(self.frame_5)
        self.Voltar.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Voltar.setObjectName("Voltar")
        self.verticalLayout_12.addWidget(self.Voltar)
        self.gridLayout_2.addWidget(self.frame_5, 6, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.Endereco_email = QtWidgets.QLineEdit(self.frame_3)
        self.Endereco_email.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Endereco_email.setObjectName("Endereco_email")
        self.verticalLayout_4.addWidget(self.Endereco_email)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 120))
        self.frame_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_2.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(60, 50, 70);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Nome_completo = QtWidgets.QLineEdit(self.frame_2)
        self.Nome_completo.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Nome_completo.setObjectName("Nome_completo")
        self.verticalLayout_2.addWidget(self.Nome_completo)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.Nascimento = QtWidgets.QDateEdit(self.frame_9)
        self.Nascimento.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Nascimento.setObjectName("Nascimento")
        self.verticalLayout_7.addWidget(self.Nascimento)
        self.gridLayout_2.addWidget(self.frame_9, 2, 3, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Cadastrar_usuario = QtWidgets.QPushButton(self.frame_10)
        self.Cadastrar_usuario.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Cadastrar_usuario.setObjectName("Cadastrar_usuario")
        self.verticalLayout.addWidget(self.Cadastrar_usuario)
        self.gridLayout_2.addWidget(self.frame_10, 6, 3, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setMinimumSize(QtCore.QSize(200, 70))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.Senha_user = QtWidgets.QLineEdit(self.frame_7)
        self.Senha_user.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Senha_user.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Senha_user.setObjectName("Senha_user")
        self.verticalLayout_3.addWidget(self.Senha_user)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addWidget(self.frame_7, 0, 2, 1, 2)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_Termos = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_Termos.setObjectName("checkBox_Termos")
        self.verticalLayout_10.addWidget(self.checkBox_Termos)
        self.checkBox_notificadcoes = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_notificadcoes.setObjectName("checkBox_notificadcoes")
        self.verticalLayout_10.addWidget(self.checkBox_notificadcoes)
        self.gridLayout_2.addWidget(self.frame_12, 5, 1, 1, 3)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.Nome_usuario = QtWidgets.QLineEdit(self.frame_6)
        self.Nome_usuario.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Nome_usuario.setObjectName("Nome_usuario")
        self.verticalLayout_6.addWidget(self.Nome_usuario)
        self.gridLayout_2.addWidget(self.frame_6, 2, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setMinimumSize(QtCore.QSize(300, 120))
        self.frame_11.setMaximumSize(QtCore.QSize(600, 130))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.CPF = QtWidgets.QLineEdit(self.frame_11)
        self.CPF.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.CPF.setText("")
        self.CPF.setObjectName("CPF")
        self.verticalLayout_9.addWidget(self.CPF)
        self.gridLayout_2.addWidget(self.frame_11, 3, 3, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_2.addWidget(self.frame_13, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Ui_Tela_Login_cadastro_user.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_Tela_Login_cadastro_user)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName("menubar")
        Ui_Tela_Login_cadastro_user.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_Tela_Login_cadastro_user)
        self.statusbar.setObjectName("statusbar")
        Ui_Tela_Login_cadastro_user.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_Tela_Login_cadastro_user)
        QtCore.QMetaObject.connectSlotsByName(Ui_Tela_Login_cadastro_user)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Nome_completo, self.Senha_user)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Senha_user, self.Endereco_email)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Endereco_email, self.Senha_verifica)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Senha_verifica, self.Nome_usuario)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Nome_usuario, self.Nascimento)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Nascimento, self.Telefone)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Telefone, self.CPF)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.CPF, self.checkBox_Termos)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.checkBox_Termos, self.checkBox_notificadcoes)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.checkBox_notificadcoes, self.Voltar)
        Ui_Tela_Login_cadastro_user.setTabOrder(self.Voltar, self.Cadastrar_usuario)

    def retranslateUi(self, Ui_Tela_Login_cadastro_user):
        _translate = QtCore.QCoreApplication.translate
        Ui_Tela_Login_cadastro_user.setWindowTitle(_translate("Ui_Tela_Login_cadastro_user", "Cadastro"))
        self.label_8.setText(_translate("Ui_Tela_Login_cadastro_user", "Digite a senha Novamente:"))
        self.label_9.setText(_translate("Ui_Tela_Login_cadastro_user", "Telefone:"))
        self.Voltar.setText(_translate("Ui_Tela_Login_cadastro_user", "Cancelar"))
        self.label_2.setText(_translate("Ui_Tela_Login_cadastro_user", "Endereço de Email:"))
        self.label.setText(_translate("Ui_Tela_Login_cadastro_user", "Nome Completo:"))
        self.label_6.setText(_translate("Ui_Tela_Login_cadastro_user", "Data de Nascimento:"))
        self.Cadastrar_usuario.setText(_translate("Ui_Tela_Login_cadastro_user", "Cadastrar"))
        self.label_5.setText(_translate("Ui_Tela_Login_cadastro_user", "Digite sua senha: "))
        self.checkBox_Termos.setText(_translate("Ui_Tela_Login_cadastro_user", "Aceite os Termos"))
        self.checkBox_notificadcoes.setText(_translate("Ui_Tela_Login_cadastro_user", "Receber notificações sobre ofertas."))
        self.label_3.setText(_translate("Ui_Tela_Login_cadastro_user", "Nome de Usuario:"))
        self.label_7.setText(_translate("Ui_Tela_Login_cadastro_user", "CPF:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Tela_Login_cadastro_user = QtWidgets.QMainWindow()
    ui = Ui_Ui_Tela_Login_cadastro_user()
    ui.setupUi(Ui_Tela_Login_cadastro_user)
    Ui_Tela_Login_cadastro_user.show()
    sys.exit(app.exec_())
