# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_ADM_jogos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_ADM_Menu(object):
    def setupUi(self, Tela_ADM_Menu):
        Tela_ADM_Menu.setObjectName("Tela_ADM_Menu")
        Tela_ADM_Menu.resize(1030, 868)
        self.centralwidget = QtWidgets.QWidget(Tela_ADM_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 3px;\n"
"padding: 8px 16px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.gridLayout.addWidget(self.frame_6, 7, 0, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.gridLayout.addWidget(self.frame_17, 3, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_21 = QtWidgets.QFrame(self.frame_4)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Cadastrar_jogo = QtWidgets.QPushButton(self.frame_21)
        self.Cadastrar_jogo.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Cadastrar_jogo.setObjectName("Cadastrar_jogo")
        self.verticalLayout_3.addWidget(self.Cadastrar_jogo)
        self.horizontalLayout_2.addWidget(self.frame_21)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Buscar_jogo = QtWidgets.QPushButton(self.frame_20)
        self.Buscar_jogo.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Buscar_jogo.setObjectName("Buscar_jogo")
        self.verticalLayout_16.addWidget(self.Buscar_jogo)
        self.horizontalLayout_2.addWidget(self.frame_20)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Remover_jogo = QtWidgets.QPushButton(self.frame_15)
        self.Remover_jogo.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Remover_jogo.setObjectName("Remover_jogo")
        self.verticalLayout_15.addWidget(self.Remover_jogo)
        self.horizontalLayout_2.addWidget(self.frame_15)
        self.frame_22 = QtWidgets.QFrame(self.frame_4)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Atualizar_jogo = QtWidgets.QPushButton(self.frame_22)
        self.Atualizar_jogo.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Atualizar_jogo.setObjectName("Atualizar_jogo")
        self.verticalLayout_17.addWidget(self.Atualizar_jogo)
        self.horizontalLayout_2.addWidget(self.frame_22)
        self.gridLayout.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame_7, 6, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_25 = QtWidgets.QFrame(self.frame_5)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.Buscar_Usuario = QtWidgets.QPushButton(self.frame_25)
        self.Buscar_Usuario.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Buscar_Usuario.setObjectName("Buscar_Usuario")
        self.verticalLayout_20.addWidget(self.Buscar_Usuario)
        self.horizontalLayout_3.addWidget(self.frame_25)
        self.frame_24 = QtWidgets.QFrame(self.frame_5)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Editar_usuario = QtWidgets.QPushButton(self.frame_24)
        self.Editar_usuario.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Editar_usuario.setObjectName("Editar_usuario")
        self.verticalLayout_19.addWidget(self.Editar_usuario)
        self.horizontalLayout_3.addWidget(self.frame_24)
        self.frame_23 = QtWidgets.QFrame(self.frame_5)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Verificar_jogos_usuario = QtWidgets.QPushButton(self.frame_23)
        self.Verificar_jogos_usuario.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.Verificar_jogos_usuario.setObjectName("Verificar_jogos_usuario")
        self.verticalLayout_18.addWidget(self.Verificar_jogos_usuario)
        self.horizontalLayout_3.addWidget(self.frame_23)
        self.frame_26 = QtWidgets.QFrame(self.frame_5)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.horizontalLayout_3.addWidget(self.frame_26)
        self.gridLayout.addWidget(self.frame_5, 5, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.gridLayout.addWidget(self.frame_9, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.gridLayout.addWidget(self.frame_11, 6, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(250, 300))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.gridLayout.addWidget(self.frame_13, 5, 1, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout.addWidget(self.frame_14, 0, 2, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_19)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.sair = QtWidgets.QPushButton(self.frame_19)
        self.sair.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.sair.setObjectName("sair")
        self.verticalLayout_2.addWidget(self.sair)
        self.gridLayout.addWidget(self.frame_19, 7, 2, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.gridLayout.addWidget(self.frame_8, 7, 1, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout.addWidget(self.frame_12, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout.addWidget(self.frame_18, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        Tela_ADM_Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tela_ADM_Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        Tela_ADM_Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tela_ADM_Menu)
        self.statusbar.setObjectName("statusbar")
        Tela_ADM_Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_ADM_Menu)
        QtCore.QMetaObject.connectSlotsByName(Tela_ADM_Menu)

    def retranslateUi(self, Tela_ADM_Menu):
        _translate = QtCore.QCoreApplication.translate
        Tela_ADM_Menu.setWindowTitle(_translate("Tela_ADM_Menu", "Tela_Admin"))
        self.label_6.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.label_7.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.Cadastrar_jogo.setText(_translate("Tela_ADM_Menu", "Cadastrar"))
        self.Buscar_jogo.setText(_translate("Tela_ADM_Menu", "Buscar"))
        self.Remover_jogo.setText(_translate("Tela_ADM_Menu", "Remover"))
        self.Atualizar_jogo.setText(_translate("Tela_ADM_Menu", "Atualizar"))
        self.label_5.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.Buscar_Usuario.setText(_translate("Tela_ADM_Menu", "Buscar"))
        self.Editar_usuario.setText(_translate("Tela_ADM_Menu", "Editar"))
        self.Verificar_jogos_usuario.setText(_translate("Tela_ADM_Menu", "Verificar jogos"))
        self.pushButton_8.setText(_translate("Tela_ADM_Menu", "PushButton"))
        self.label_9.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.label_2.setText(_translate("Tela_ADM_Menu", "Jogos"))
        self.label_11.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.textBrowser.setHtml(_translate("Tela_ADM_Menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Bem vindo a Tela do administrador dos serviços referentes ao Jogue Agora</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Nessa tela é possivel:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    JOGOS:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    1- Cadastrar Novos Jogos</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    2- Buscar Jogos</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    3- Remover Jogos</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    USUÁRIOS:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    1- Buscar Usuários</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    2- Mudar Saldo</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">    3- Verificar Jogos da Conta</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.pushButton.setText(_translate("Tela_ADM_Menu", "PushButton"))
        self.sair.setText(_translate("Tela_ADM_Menu", "Voltar"))
        self.label_12.setText(_translate("Tela_ADM_Menu", "TextLabel"))
        self.label_4.setText(_translate("Tela_ADM_Menu", "Usuarios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_ADM_Menu = QtWidgets.QMainWindow()
    ui = Ui_Tela_ADM_Menu()
    ui.setupUi(Tela_ADM_Menu)
    Tela_ADM_Menu.show()
    sys.exit(app.exec_())
