# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastrar_jogos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 3px;\n"
"padding: 8px 16px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.Desenvolvedor = QtWidgets.QLineEdit(self.frame_3)
        self.Desenvolvedor.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Desenvolvedor.setObjectName("Desenvolvedor")
        self.verticalLayout_3.addWidget(self.Desenvolvedor)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.RE_CPU = QtWidgets.QLineEdit(self.frame_5)
        self.RE_CPU.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.RE_CPU.setObjectName("RE_CPU")
        self.verticalLayout_5.addWidget(self.RE_CPU)
        self.gridLayout.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.Genero = QtWidgets.QLineEdit(self.frame_11)
        self.Genero.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Genero.setObjectName("Genero")
        self.verticalLayout_12.addWidget(self.Genero)
        self.gridLayout.addWidget(self.frame_11, 2, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.RE_Memoria = QtWidgets.QLineEdit(self.frame_7)
        self.RE_Memoria.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.RE_Memoria.setObjectName("RE_Memoria")
        self.verticalLayout_7.addWidget(self.RE_Memoria)
        self.gridLayout.addWidget(self.frame_7, 8, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.RE_GPU = QtWidgets.QLineEdit(self.frame_6)
        self.RE_GPU.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.RE_GPU.setObjectName("RE_GPU")
        self.verticalLayout_6.addWidget(self.RE_GPU)
        self.gridLayout.addWidget(self.frame_6, 6, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.Preco = QtWidgets.QDoubleSpinBox(self.frame_12)
        self.Preco.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Preco.setObjectName("Preco")
        self.horizontalLayout.addWidget(self.Preco)
        self.gridLayout.addWidget(self.frame_12, 4, 1, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_14)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.RE_Sistema = QtWidgets.QLineEdit(self.frame_14)
        self.RE_Sistema.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.RE_Sistema.setObjectName("RE_Sistema")
        self.verticalLayout_15.addWidget(self.RE_Sistema)
        self.gridLayout.addWidget(self.frame_14, 8, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.RE_Outros = QtWidgets.QLineEdit(self.frame_10)
        self.RE_Outros.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.RE_Outros.setObjectName("RE_Outros")
        self.verticalLayout_11.addWidget(self.RE_Outros)
        self.gridLayout.addWidget(self.frame_10, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.Distribuidor = QtWidgets.QLineEdit(self.frame_4)
        self.Distribuidor.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Distribuidor.setObjectName("Distribuidor")
        self.verticalLayout_4.addWidget(self.Distribuidor)
        self.gridLayout.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cadastrar = QtWidgets.QPushButton(self.frame_8)
        self.cadastrar.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.cadastrar.setObjectName("cadastrar")
        self.verticalLayout_8.addWidget(self.cadastrar)
        self.gridLayout.addWidget(self.frame_8, 11, 1, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_13)
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.Desconto = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.Desconto.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Desconto.setObjectName("Desconto")
        self.horizontalLayout_2.addWidget(self.Desconto)
        self.gridLayout.addWidget(self.frame_13, 6, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Nome_jogo = QtWidgets.QLineEdit(self.frame_2)
        self.Nome_jogo.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.Nome_jogo.setObjectName("Nome_jogo")
        self.verticalLayout_2.addWidget(self.Nome_jogo)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.RE_armazenamento = QtWidgets.QLineEdit(self.frame_9)
        self.RE_armazenamento.setStyleSheet("/* Aplicando o estilo antigo com tons de cinza */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(218, 218, 218);\n"
"background-color: rgb(60, 60, 60);\n"
"border: none; /* Removendo o contorno das bordas nos quadros */\n"
"border-radius: 0; /* Removendo a borda arredondada nos campos de digitação */\n"
"padding: 8px 16px;\n"
"border-width: 1px; /* Adicionando borda de 1px nos campos de digitação */\n"
"border-style: solid; /* Definindo o estilo da borda como sólido */\n"
"border-color: rgb(150, 150, 150); /* Definindo a cor da borda dos campos de digitação */\n"
"")
        self.RE_armazenamento.setObjectName("RE_armazenamento")
        self.verticalLayout_10.addWidget(self.RE_armazenamento)
        self.gridLayout.addWidget(self.frame_9, 0, 1, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cancelar = QtWidgets.QPushButton(self.frame_16)
        self.cancelar.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(218, 218, 218);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-color: beige;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(88, 88, 88); /* Cor de fundo quando o botão é destacado */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 40, 40); /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"")
        self.cancelar.setObjectName("cancelar")
        self.verticalLayout_9.addWidget(self.cancelar)
        self.gridLayout.addWidget(self.frame_16, 11, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Nome_jogo, self.Desenvolvedor)
        MainWindow.setTabOrder(self.Desenvolvedor, self.Distribuidor)
        MainWindow.setTabOrder(self.Distribuidor, self.RE_CPU)
        MainWindow.setTabOrder(self.RE_CPU, self.RE_GPU)
        MainWindow.setTabOrder(self.RE_GPU, self.RE_Memoria)
        MainWindow.setTabOrder(self.RE_Memoria, self.RE_armazenamento)
        MainWindow.setTabOrder(self.RE_armazenamento, self.RE_Outros)
        MainWindow.setTabOrder(self.RE_Outros, self.Genero)
        MainWindow.setTabOrder(self.Genero, self.Preco)
        MainWindow.setTabOrder(self.Preco, self.Desconto)
        MainWindow.setTabOrder(self.Desconto, self.RE_Sistema)
        MainWindow.setTabOrder(self.RE_Sistema, self.cancelar)
        MainWindow.setTabOrder(self.cancelar, self.cadastrar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastrar Jogos"))
        self.label_2.setText(_translate("MainWindow", "Desenvolvedor"))
        self.label_4.setText(_translate("MainWindow", "Requisitos CPU"))
        self.label_9.setText(_translate("MainWindow", "Gênero"))
        self.label_6.setText(_translate("MainWindow", "Requisitos Memoria"))
        self.label_5.setText(_translate("MainWindow", "Requisitos GPU"))
        self.label_10.setText(_translate("MainWindow", "Preco:"))
        self.label_12.setText(_translate("MainWindow", "Requisitos Sistema Operacional"))
        self.label_8.setText(_translate("MainWindow", "Requisitos Outros"))
        self.label_3.setText(_translate("MainWindow", "Distribuidor"))
        self.cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_11.setText(_translate("MainWindow", "Desconto:"))
        self.label.setText(_translate("MainWindow", "Nome"))
        self.label_7.setText(_translate("MainWindow", "Requisitos Armazenamento"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
